// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

<<<<<<< HEAD
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
=======
import { application } from "./application"
>>>>>>> dep

import HomeController from "./home_controller"
application.register("home", HomeController)

import HumburgerController from "./humburger_controller"
application.register("humburger", HumburgerController)

import PongController from "./pong_controller"
application.register("pong", PongController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import ToastController from "./toast_controller"
<<<<<<< HEAD
application.register("toast", ToastController)
=======
application.register("toast", ToastController)
>>>>>>> dep
